### ISSUE TITLE
Запрос на добавление ElasticSearch

### ISSUE THREAD

**Issue by leech001** [kuznetsovin/egts-protocol#7]
Просьба рассмотреть предложение о добавления коннектора к вашему решению для возможности сохранения треков в ElasticSearch.
Судя по описанию вы очень похоже храните объекты в других БД в виде JSON. Так что по логике проблем не должно возникнуть.
Заранее спасибо.

**Comment by nekludoff** [comment]
для эластика код все еще нужен?

**Comment by leech001** [comment]
> для эластика код все еще нужен?

Думаю что наверное уже нет. Три года ждали :)
